# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('TIKTOK', 'TikTok'), ('SOUNDCLOUD', 'SoundCloud')], max_length=15)),
                ('key_encrypted', models.TextField(help_text='Encrypted API token credentials')),
                ('daily_quota', models.IntegerField(default=1000)),
                ('used_today', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('follower_count', models.IntegerField()),
                ('post_count', models.IntegerField()),
                ('was_alive', models.BooleanField(default=True)),
                ('recent_post_dates', models.JSONField(blank=True, default=list)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('24H', '24-Hour Survival Check'), ('48H', '48-Hour Survival Check')], max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('comment_alive', models.BooleanField(default=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('comment_text_now', models.TextField(blank=True, null=True)),
                ('delta_from_original', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survival_checks', to='submissions.submission')),
            ],
        ),
    ]
