# Generated by Django 5.0.14 on 2026-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='platform',
            field=models.CharField(choices=[('IG', 'Instagram'), ('YT', 'YouTube'), ('TIKTOK', 'TikTok')], max_length=15),
        ),
    ]
