# Generated by Django 5.0.14 on 2026-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_apikey_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='platform',
            field=models.CharField(choices=[('IG', 'Instagram'), ('YT', 'YouTube'), ('TIKTOK', 'TikTok'), ('X', 'Twitter')], max_length=15),
        ),
    ]
