# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_details', models.JSONField(blank=True, default=dict, help_text='Registration payload (e.g. ABN, address)')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=15)),
                ('brief_md', models.TextField(help_text='Markdown campaign brief guidelines')),
                ('tone_guidance', models.TextField(blank=True, help_text='Specific tone directives')),
                ('target_post_url_default', models.URLField(blank=True, null=True)),
                ('keyword_default', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_rate_per_approved_task', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payout_cadence', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=15)),
                ('payout_method_required', models.CharField(choices=[('AIRTM', 'Airtm'), ('PAYPAL', 'PayPal'), ('CRYPTO', 'Crypto'), ('ANY', 'Any')], default='ANY', max_length=15)),
                ('payout_min_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('terms_md', models.TextField(help_text='Markdown terms shown to writers before claim')),
                ('ai_detection_strictness', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=15)),
                ('credibility_thresholds', models.JSONField(blank=True, default=dict, help_text='Minimum followers/posts requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.company')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired')], default='OPEN', max_length=15)),
                ('target_post_url', models.URLField(blank=True, help_text="Specific target post (defaults to project's default)", null=True)),
                ('keyword', models.CharField(blank=True, help_text="Specific keyword (defaults to project's default)", max_length=100, null=True)),
                ('remaining_count', models.IntegerField(default=1)),
                ('total_count', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
    ]
