# Generated by Django 5.0.14 on 2026-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_starter',
            field=models.BooleanField(default=False, help_text='Practice project shown to fresh users'),
        ),
        migrations.AddField(
            model_name='project',
            name='tone',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('product', 'Product'), ('story', 'Story'), ('disagreement', 'Disagreement'), ('brand', 'Brand')], default='lifestyle', max_length=20),
        ),
    ]
