# Generated by Django 5.0.14 on 2026-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, default='', help_text='Display name shown in UI', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='starter_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='starter_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tutorial_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wizard_step',
            field=models.CharField(choices=[('signup', 'Sign up'), ('verify-email', 'Verify email'), ('welcome', 'Welcome'), ('link-account', 'Link account'), ('attest', 'Attest'), ('tutorial', 'Tutorial'), ('first-task', 'First task'), ('done', 'Done')], default='signup', max_length=20),
        ),
    ]
