# Generated by Django 5.0.14 on 2026-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_attested_at_user_email_verified_user_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('IG', 'Instagram'), ('YT', 'YouTube'), ('TIKTOK', 'TikTok')], max_length=15),
        ),
    ]
