# Generated by Django 5.0.14 on 2026-05-27 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_socialaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('real_tasks_unlocked', 'Real Tasks Unlocked'), ('promoted_to_reviewer', 'Promoted To Reviewer'), ('account_held', 'Account On Hold'), ('system', 'System Notice')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='accounts_no_recipie_799191_idx'), models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx')],
            },
        ),
    ]
