# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUBMITTED', 'Submitted'), ('VOIDED', 'Voided')], default='ACTIVE', max_length=15)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_url', models.URLField()),
                ('comment_text_snapshot', models.TextField()),
                ('comment_account_handle', models.CharField(max_length=100)),
                ('proof_type', models.CharField(choices=[('URL', 'URL Verification'), ('SCREENSHOT', 'Screenshot Proof')], default='URL', max_length=15)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('paste_event_count', models.IntegerField(default=0)),
                ('keypress_count', models.IntegerField(default=0)),
                ('time_to_compose_seconds', models.IntegerField(default=0)),
                ('attestation_signed', models.BooleanField(default=False)),
                ('ai_likelihood_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HELD', 'Held for Review')], default='PENDING', max_length=15)),
                ('rating_final', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('base_payout', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('bonus_payout', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submissions.claim')),
            ],
        ),
    ]
