# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to=settings.AUTH_USER_MODEL)),
                ('submissions', models.ManyToManyField(related_name='bundles', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Anchored quality rating (1 to 5 stars)')),
                ('justification_text', models.TextField(help_text='Mandatory textual justification for the rating')),
                ('feels_ai_flag', models.BooleanField(default=False, help_text='Ticked if the comment reads like a chatbot output')),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('T1', 'Tier 1'), ('T2', 'Tier 2'), ('ADMIN', 'Admin Reviewer')], default='T1', max_length=15)),
                ('rolling_accuracy_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('reviews_completed', models.IntegerField(default=0)),
                ('current_pay_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('daily_review_count', models.IntegerField(default=0)),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviewer Stats',
            },
        ),
    ]
