# Generated by Django 5.0.14 on 2026-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_authoritative',
            field=models.BooleanField(default=False, help_text='True if this review was the authoritative decision maker'),
        ),
    ]
