# Generated by Django 5.0.14 on 2026-05-29 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_is_authoritative'),
        ('submissions', '0003_claim_indexes_constraint_submission_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer'), name='review_unique_per_submission_reviewer'),
        ),
    ]
