# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Report'), ('EXPORTED', 'Exported to Company'), ('CONFIRMED_PAID', 'Confirmed Paid')], default='DRAFT', max_length=20)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_company_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_received_at', models.DateTimeField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, help_text='R2 CSV payout export spreadsheet link', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Payout Batches',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('kind', models.CharField(choices=[('BASE', 'Base Payout'), ('BONUS', 'Engagement Bonus'), ('REFERRAL', 'Referral Reward'), ('REVIEW_PAY', 'Review Compensation')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_PAYOUT', 'Pending Payout'), ('EXPORTED', 'Exported in Batch'), ('PAID', 'Paid Successfully')], default='PENDING_PAYOUT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='projects.project')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='submissions.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='earnings.payoutbatch')),
            ],
        ),
    ]
