# Generated by Django 5.0.14 on 2026-05-29 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_earning_unique_payout_per_submission_kind'),
        ('projects', '0002_project_is_starter_project_tone'),
        ('submissions', '0003_claim_indexes_constraint_submission_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='earning',
            constraint=models.UniqueConstraint(condition=models.Q(('submission__isnull', False), ('kind', 'REVIEW_PAY')), fields=('submission', 'user', 'kind'), name='earning_unique_review_pay_per_reviewer'),
        ),
    ]
