# Generated by Django 5.0.14 on 2026-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=12)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_discord_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARN', 'Warning'), ('CRIT', 'Critical Exception')], default='WARN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('current_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
