# Generated by Django 5.0.14 on 2026-05-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StylometricBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_sentence_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('vocabulary_diversity_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('punctuation_signature', models.JSONField(blank=True, default=dict)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('built_from_submissions', models.ManyToManyField(related_name='stylometric_baselines', to='submissions.submission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stylometric_baseline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
